#pragma once

const int PIXELS_PER_SLOT = 47;
const int INVENTORY_SLOTS = 12;

enum FRAME_TYPES {
    FRAME_TYPE_NORMAL = 0,
    FRAME_TYPE_MAGIC = 1,
    FRAME_TYPE_RARE = 2,
    FRAME_TYPE_UNIQUE = 3,
    FRAME_TYPE_GEM = 4,
    FRAME_TYPE_CURRENCY = 5,
};

enum ELEMENTAL_DAMAGE_TYPES {
    ED_FIRE = 4,
    ED_COLD = 5,
    ED_LIGHTNING = 6,
};

const int LINKH_HEIGHT = 16;
const int LINKH_WIDTH = 38;
const int LINKV_HEIGHT = LINKH_WIDTH;
const int LINKV_WIDTH = LINKH_HEIGHT;

const int MAX_EXPANDABLE_ITEMS = 1000;

const int PIXELS_PER_MINIMAP_SLOT = 10;
const int MINIMAP_SIZE = INVENTORY_SLOTS * PIXELS_PER_MINIMAP_SLOT;
